### ISSUE TITLE
Gmail API error

### ISSUE THREAD

**Issue by davesteele** [LeoIannacone/goopg#34]
"Sign and Send" is resulting in the following log entries.

    2018-11-03 14:37:03,415:INFO:Gmail:getting message #msg-a:r-1184333689291609288
    2018-11-03 14:37:03,607:ERROR:CommandHandler:<HttpError 400 when requesting 
    https://www.googleapis.com/gmail/v1/users/me/messages/%23msg-a%3Ar-1184333689291609288? 
    alt=json&format=raw returned "Invalid id value">
    Traceback (most recent call last):
      File "/usr/share/goopg/commandhandler.py", line 87, in sign
        draft = self.gmail.get(id)
      File "/usr/share/goopg/gmail/__init__.py", line 132, in get
        message = self.messages.get(userId='me', id=id, format='raw').execute()
      File "/usr/lib/python2.7/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
        return wrapped(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/googleapiclient/http.py", line 838, in execute
        raise HttpError(resp, content, uri=self.uri)
    HttpError: <HttpError 400 when requesting 
    https://www.googleapis.com/gmail/v1/users/me/messages/%23msg-a%3Ar-1184333689291609288? 
    alt=json&format=raw returned "Invalid id value">

**Comment by LeoIannacone** [comment]
Does this always happen ?

**Comment by davesteele** [comment]
Yes. Multiple systems.

**Comment by davesteele** [comment]
Logged as Debian bug [918144](https://bugs.debian.org/918144) (RC Critical).

**Comment by davesteele** [comment]
Marked for autoremoval [1 Feb](https://tracker.debian.org/pkg/goopg). Freeze for the next stable starts 2 Feb.

**Comment by davesteele** [comment]
Removed from Debian Unstable:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949118
